<?php
/**
 * Array that stores the custom fields
 *
 * @package WordPress
 * @subpackage Struck
 * @since Struck 1.0
 */
if( function_exists('register_field_group') ):

	register_field_group(array (
		'key' => 'group_546e69383a9e7',
		'title' => 'Page Title Options',
		'fields' => array (
			array (
				'key' => 'field_54e7919f8b0b1',
				'label' => 'Display Title',
				'name' => 'display_title',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_54aef7e9131f5',
				'label' => 'Title Alignment',
				'name' => 'title_alignment',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54e7919f8b0b1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'left' => 'Left',
					'center' => 'Center',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_546e69451c6d1',
				'label' => 'Subtitle',
				'name' => 'subtitle',
				'prefix' => '',
				'type' => 'text',
				'instructions' => 'Write an optional subtitle for your page.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54e7919f8b0b1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '(optional)',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_546e699c1c6d2',
				'label' => 'Title Area Background Color',
				'name' => 'title_area_background_color',
				'prefix' => '',
				'type' => 'color_picker',
				'instructions' => 'Background color behind text.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54e7919f8b0b1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#f3f3f3',
			),
			array (
				'key' => 'field_546e69e71c6d3',
				'label' => 'Title Area Background Color Opacity',
				'name' => 'title_area_background_color_opacity',
				'prefix' => '',
				'type' => 'number',
				'instructions' => 'Set an opacity for your background color. Useful for showing the featured image behind it.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54e7919f8b0b1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 100,
				'step' => 5,
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_546e6a311c6d4',
				'label' => 'Title Area Text Color',
				'name' => 'title_area_text_color',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54e7919f8b0b1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'white' => 'White',
					'black' => 'Black',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'black',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'custom_fields',
		),
	));

	register_field_group(array (
		'key' => 'group_54c98ffb8e67d',
		'title' => 'Portfolio Title Options',
		'fields' => array (
			array (
				'key' => 'field_54c9902f1d327',
				'label' => 'Show Title',
				'name' => 'show_title',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => 'Turn on off the title for this portfolio item.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_54c990141d326',
				'label' => 'Subheadline',
				'name' => 'subheadline',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '(Optional) Appears above the title.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_54d4da9f0cc32',
				'label' => 'Title Area Background Image',
				'name' => 'background_image',
				'prefix' => '',
				'type' => 'image',
				'instructions' => 'Image that will appear behind the background',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_54c98ffb96ffa',
				'label' => 'Intro Text',
				'name' => 'intro_text',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '(Optional) Write an intro for your post. It will be displayed above your content.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '(optional)',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'custom_fields',
		),
	));

	register_field_group(array (
		'key' => 'group_54c6e6c2a14e9',
		'title' => 'Post Title Options',
		'fields' => array (
			array (
				'key' => 'field_54c6e6c2ab273',
				'label' => 'Intro Text',
				'name' => 'intro_text',
				'prefix' => '',
				'type' => 'text',
				'instructions' => 'Write an intro for your post. It will be displayed above your content.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '(optional)',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'custom_fields',
		),
	));

	register_field_group(array (
		'key' => 'group_5400f5d67ab19',
		'title' => 'Sections',
		'fields' => array (
			array (
				'key' => 'field_5485d2954e6b9',
				'label' => 'Sections',
				'name' => '',
				'prefix' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
			),
			array (
				'key' => 'field_5400f6493c225',
				'label' => 'Sections',
				'name' => 'sections',
				'prefix' => '',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Add Section',
				'min' => '',
				'max' => '',
				'layouts' => array (
					array (
						'key' => '5400f6ce3c229',
						'name' => 'text-image',
						'label' => 'Text and Image Section',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_54ac39d40f53c',
								'label' => 'Title',
								'name' => '',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'left',
							),
							array (
								'key' => 'field_5445484a8ed14',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'prefix' => '',
								'type' => 'text',
								'instructions' => '(Optional) A subtitle for your section. It will appear above your title.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'readonly' => 0,
								'disabled' => 0,
							),
							array (
								'key' => 'field_5445486c8ed15',
								'label' => 'Title',
								'name' => 'title',
								'prefix' => '',
								'type' => 'text',
								'instructions' => '(Optional) A title for your section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'readonly' => 0,
								'disabled' => 0,
							),
							array (
								'key' => 'field_5453d71f8ccc7',
								'label' => 'Horizontal Layout',
								'name' => 'text_layout',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => 50,
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'left' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/left-align.jpg" alt="Align Left" />',
									'center' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/center-align.jpg"" alt="Align Center" />',
									'right' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/right-align.jpg"" alt="Align Right" />',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_54be9488db54c',
								'label' => 'Vertical Alignment',
								'name' => 'vertical_alignment',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => 50,
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'top' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/top-align.jpg" alt="Align Top" />',
									'middle' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/middle-align.jpg"" alt="Align Middle" />',
									'bottom' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/bottom-align.jpg"" alt="Align Bottom" />',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'middle',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_54526d93cc94d',
								'label' => 'Content',
								'name' => '',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
							),
							array (
								'key' => 'field_5445487b8ed16',
								'label' => 'Content',
								'name' => 'content',
								'prefix' => '',
								'type' => 'wysiwyg',
								'instructions' => '(Optional) A additional text for your section. Appears below the title.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
							),
							array (
								'key' => 'field_54ac39ea0f53d',
								'label' => 'Buttons',
								'name' => '',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
							),
							array (
								'key' => 'field_5485ed08c3c28',
								'label' => 'Buttons',
								'name' => 'buttons',
								'prefix' => '',
								'type' => 'repeater',
								'instructions' => '(Optional) Click add button to add a button to your section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'min' => '',
								'max' => '',
								'layout' => 'block',
								'button_label' => 'Add Button',
								'sub_fields' => array (
									array (
										'key' => 'field_5485ed63c3c2a',
										'label' => 'Button Text',
										'name' => 'button_text',
										'prefix' => '',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
										'readonly' => 0,
										'disabled' => 0,
									),
									array (
										'key' => 'field_5485ed23c3c29',
										'label' => 'Button Style',
										'name' => 'button_style',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'button' => 'Button',
											'link' => 'Regular Link',
											'play' => 'Play Icon',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'button',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_5485ed7dc3c2b',
										'label' => 'Button Link',
										'name' => 'button_link',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'next' => 'Next Section',
											'page' => 'Page / Post',
											'url' => 'Custom External URL',
											'lightbox' => 'Lightbox',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_5485ee06c3c2c',
										'label' => 'Button Link',
										'name' => 'page_post_link',
										'prefix' => '',
										'type' => 'page_link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5485ed7dc3c2b',
													'operator' => '==',
													'value' => 'page',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => '',
										'taxonomy' => '',
										'allow_null' => 0,
										'multiple' => 0,
									),
									array (
										'key' => 'field_5485ee2cc3c2d',
										'label' => 'Button Url',
										'name' => 'button_url',
										'prefix' => '',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5485ed7dc3c2b',
													'operator' => '==',
													'value' => 'url',
												),
											),
											array (
												array (
													'field' => 'field_5485ed7dc3c2b',
													'operator' => '==',
													'value' => 'lightbox',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => 'http://',
									),
								),
							),
							array (
								'key' => 'field_5453d7578ccc8',
								'label' => 'Image',
								'name' => 'image',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
							),
							array (
								'key' => 'field_5453d7878ccc9',
								'label' => 'Image',
								'name' => 'images',
								'prefix' => '',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_54aaef14b5aab',
								'label' => 'Image Link',
								'name' => 'image_link',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'lightbox' => 'Image Lightbox',
									'custom' => 'Custom URL',
									'none' => 'None',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'lightbox',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_54aaef56b5aac',
								'label' => 'Custom URL',
								'name' => 'custom_url_image',
								'prefix' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54aaef14b5aab',
											'operator' => '==',
											'value' => 'custom',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'http://',
							),
							array (
								'key' => 'field_54526db5cc94e',
								'label' => 'Background',
								'name' => '',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'left',
							),
							array (
								'key' => 'field_544548ce8ed18',
								'label' => 'Text, Logo and Navigation Color',
								'name' => 'text_color',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => 'For dark backgrounds, you may want to select white.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'white' => 'White',
									'black' => 'Black',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'black',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_5400f6d93c22a',
								'label' => 'Background',
								'name' => 'background',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'color' => 'Color Background',
									'image' => 'Image Background',
									'video' => 'Video Background',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'color',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_544176ac8f597',
								'label' => 'Video Type',
								'name' => 'video_type',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'youtube' => 'YouTube',
									'self' => 'Self Hosted',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_544176ea8f598',
								'label' => 'Youtube Video',
								'name' => 'youtube_video',
								'prefix' => '',
								'type' => 'url',
								'instructions' => 'Enter the Youtube Video URL.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'video',
										),
										array (
											'field' => 'field_544176ac8f597',
											'operator' => '==',
											'value' => 'youtube',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'http://',
							),
							array (
								'key' => 'field_544177188f59a',
								'label' => 'Video Mp4 URL',
								'name' => 'video_mp4_url',
								'prefix' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'video',
										),
										array (
											'field' => 'field_544176ac8f597',
											'operator' => '==',
											'value' => 'self',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
							array (
								'key' => 'field_5441781dcb0ba',
								'label' => 'Video WebM URL',
								'name' => 'video_webm_url',
								'prefix' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'video',
										),
										array (
											'field' => 'field_544176ac8f597',
											'operator' => '==',
											'value' => 'self',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
							array (
								'key' => 'field_54d64e84696ca',
								'label' => 'Video Image PlaceHolder',
								'name' => 'video_image_placeholder',
								'prefix' => '',
								'type' => 'image',
								'instructions' => 'Placeholder for images. These will display during the loading of videos and for mobile devices where video backgrounds are disabled.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_544178a93b102',
								'label' => 'Background Image',
								'name' => 'background_image',
								'prefix' => '',
								'type' => 'image',
								'instructions' => 'Image should be at least 1500px wide.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'image',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
							),
							array (
								'key' => 'field_544178d63b103',
								'label' => 'Background Color',
								'name' => 'background_color',
								'prefix' => '',
								'type' => 'color_picker',
								'instructions' => 'Solid background color for your section.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'color',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array (
								'key' => 'field_5441784ca7777',
								'label' => 'Overlay Color',
								'name' => 'overlay',
								'prefix' => '',
								'type' => 'color_picker',
								'instructions' => 'Overlay color above videos and images.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'image',
										),
									),
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array (
									'width' => 50,
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array (
								'key' => 'field_54417937d09c2',
								'label' => 'Overlay Opacity',
								'name' => 'overlay_opacity',
								'prefix' => '',
								'type' => 'number',
								'instructions' => 'Percentage opacity for the overlay.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'image',
										),
									),
									array (
										array (
											'field' => 'field_5400f6d93c22a',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array (
									'width' => 50,
									'class' => '',
									'id' => '',
								),
								'default_value' => 30,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => 100,
								'step' => 5,
								'readonly' => 0,
								'disabled' => 0,
							),
							array (
								'key' => 'field_54bec83c6c66a',
								'label' => 'Section Caption',
								'name' => 'credits',
								'prefix' => '',
								'type' => 'textarea',
								'instructions' => 'Add a caption or credits for the section in the lower right corner.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'i.e. Image By John Doe',
								'maxlength' => '',
								'rows' => 2,
								'new_lines' => 'br',
								'readonly' => 0,
								'disabled' => 0,
							),
							array (
								'key' => 'field_54a463c1166a2',
								'label' => 'Extras',
								'name' => '',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
							),
							array (
								'key' => 'field_5487321f824f7',
								'label' => 'Scroll Indicator Arrow',
								'name' => 'scroll_arrow',
								'prefix' => '',
								'type' => 'true_false',
								'instructions' => 'Turn on/off the arrow indicator to scroll to next section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 1,
							),
							array (
								'key' => 'field_54a463f0166a3',
								'label' => 'Animations',
								'name' => 'animations',
								'prefix' => '',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 1,
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '5494640049dd7',
						'name' => 'text-image-slides',
						'label' => 'Text and Image Slides',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_5494642649dd8',
								'label' => 'Slides',
								'name' => 'slides',
								'prefix' => '',
								'type' => 'repeater',
								'instructions' => 'Click Add Slide to add a new slide to the section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => 'slide-layout',
									'id' => '',
								),
								'min' => '',
								'max' => '',
								'layout' => 'block',
								'button_label' => 'Add Slide',
								'sub_fields' => array (
									array (
										'key' => 'field_54ac3bbc49b2b',
										'label' => 'Title',
										'name' => '',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'left',
									),
									array (
										'key' => 'field_54946592c909d',
										'label' => 'Subtitle',
										'name' => 'subtitle',
										'prefix' => '',
										'type' => 'text',
										'instructions' => 'Enter a subtitle.	It will appear above your title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
										'readonly' => 0,
										'disabled' => 0,
									),
									array (
										'key' => 'field_5494654bc909c',
										'label' => 'Title',
										'name' => 'title',
										'prefix' => '',
										'type' => 'text',
										'instructions' => 'Add a title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
										'readonly' => 0,
										'disabled' => 0,
									),
									array (
										'key' => 'field_54946516c909b',
										'label' => 'Horizontal Layout',
										'name' => 'text_layout',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 50,
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'left' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/left-align.jpg" alt="Align Left" />',
											'center' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/center-align.jpg"" alt="Align Center" />',
											'right' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/right-align.jpg"" alt="Align Right" />',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_54be961172225',
										'label' => 'Vertical Alignment',
										'name' => 'vertical_alignment',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => 50,
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'top' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/top-align.jpg" alt="Align Top" />',
											'middle' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/middle-align.jpg"" alt="Align Middle" />',
											'bottom' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/bottom-align.jpg"" alt="Align Bottom" />',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'middle',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_549464a349dd9',
										'label' => 'Content',
										'name' => '',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
									),
									array (
										'key' => 'field_549465cbc909e',
										'label' => 'Content',
										'name' => 'content',
										'prefix' => '',
										'type' => 'wysiwyg',
										'instructions' => 'Add an intro or short description.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
									),
									array (
										'key' => 'field_54b03f6c5d862',
										'label' => 'Buttons',
										'name' => '',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
									),
									array (
										'key' => 'field_549465fac909f',
										'label' => 'Buttons',
										'name' => 'buttons',
										'prefix' => '',
										'type' => 'repeater',
										'instructions' => 'Click add button to add a button to your section.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'min' => '',
										'max' => '',
										'layout' => 'block',
										'button_label' => 'Add Button',
										'sub_fields' => array (
											array (
												'key' => 'field_54946616c90a0',
												'label' => 'Button Style',
												'name' => 'button_style',
												'prefix' => '',
												'type' => 'radio',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array (
													'button' => 'Button',
													'link' => 'Regular Link',
													'play' => 'Play Icon',
												),
												'other_choice' => 0,
												'save_other_choice' => 0,
												'default_value' => 'button',
												'layout' => 'horizontal',
											),
											array (
												'key' => 'field_54946651c90a1',
												'label' => 'Button Text',
												'name' => 'button_text',
												'prefix' => '',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
												'readonly' => 0,
												'disabled' => 0,
											),
											array (
												'key' => 'field_5494666bc90a2',
												'label' => 'Button Link',
												'name' => 'button_link',
												'prefix' => '',
												'type' => 'radio',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array (
													'next' => 'Next Section',
													'nextslide' => 'Next Slide',
													'page' => 'Page / Post',
													'url' => 'Custom External URL',
													'lightbox' => 'Lightbox',
												),
												'other_choice' => 0,
												'save_other_choice' => 0,
												'default_value' => '',
												'layout' => 'horizontal',
											),
											array (
												'key' => 'field_549466b6c90a3',
												'label' => 'Button Link',
												'name' => 'page_post_link',
												'prefix' => '',
												'type' => 'page_link',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_5494666bc90a2',
															'operator' => '==',
															'value' => 'page',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'post_type' => '',
												'taxonomy' => '',
												'allow_null' => 0,
												'multiple' => 0,
											),
											array (
												'key' => 'field_54946727c90a4',
												'label' => 'Button Url',
												'name' => 'button_url',
												'prefix' => '',
												'type' => 'url',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_5494666bc90a2',
															'operator' => '==',
															'value' => 'url',
														),
													),
													array (
														array (
															'field' => 'field_5494666bc90a2',
															'operator' => '==',
															'value' => 'lightbox',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => 'http://',
											),
										),
									),
									array (
										'key' => 'field_549464b349dda',
										'label' => 'Image',
										'name' => 'image',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
									),
									array (
										'key' => 'field_549467e855992',
										'label' => 'Image',
										'name' => 'images',
										'prefix' => '',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_54aaf3d828125',
										'label' => 'Image Link',
										'name' => 'image_link',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'lightbox' => 'Image Lightbox',
											'custom' => 'Custom URL',
											'none' => 'None',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'lightbox',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_54aaf41628126',
										'label' => 'Custom URL',
										'name' => 'custom_url_image',
										'prefix' => '',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54aaf3d828125',
													'operator' => '==',
													'value' => 'custom',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => 'http://',
									),
									array (
										'key' => 'field_549464c049ddb',
										'label' => 'Background',
										'name' => '',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
									),
									array (
										'key' => 'field_5494681155993',
										'label' => 'Text, Logo and Navigation Color',
										'name' => 'text_color',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => 'For dark backgrounds, you may want to select white.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'white' => 'White',
											'black' => 'Black',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'black',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_5494684055994',
										'label' => 'Background',
										'name' => 'background',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'color' => 'Color Background',
											'image' => 'Image Background',
											'video' => 'Video Background',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'color',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_5494690c55997',
										'label' => 'Video Type',
										'name' => 'video_type',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'video',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'youtube' => 'YouTube',
											'self' => 'Self Hosted',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_5494693a55998',
										'label' => 'Youtube Video',
										'name' => 'youtube_video',
										'prefix' => '',
										'type' => 'url',
										'instructions' => 'Enter the youtube video URL.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'video',
												),
												array (
													'field' => 'field_5494690c55997',
													'operator' => '==',
													'value' => 'youtube',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => 'http://',
									),
									array (
										'key' => 'field_5494699a5599a',
										'label' => 'Video Mp4 URL',
										'name' => 'video_mp4_url',
										'prefix' => '',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'video',
												),
												array (
													'field' => 'field_5494690c55997',
													'operator' => '==',
													'value' => 'self',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
									),
									array (
										'key' => 'field_549469ca5599c',
										'label' => 'Video WebM URL',
										'name' => 'video_webm_url',
										'prefix' => '',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'video',
												),
												array (
													'field' => 'field_5494690c55997',
													'operator' => '==',
													'value' => 'self',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
									),
									array (
										'key' => 'field_54da2ed1dea16',
										'label' => 'Video Image PlaceHolder',
										'name' => 'video_image_placeholder',
										'prefix' => '',
										'type' => 'image',
										'instructions' => 'Placeholder for images. These will display during the loading of videos and for mobile devices where video backgrounds are disabled.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'video',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_54946a4883c83',
										'label' => 'Background Image',
										'name' => 'background_image',
										'prefix' => '',
										'type' => 'image',
										'instructions' => 'Image should be at least 1500px wide.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'image',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'medium',
										'library' => 'all',
									),
									array (
										'key' => 'field_54946a7783c84',
										'label' => 'Background Color',
										'name' => 'background_color',
										'prefix' => '',
										'type' => 'color_picker',
										'instructions' => 'Solid background color for your section.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'color',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '#ffffff',
									),
									array (
										'key' => 'field_5494686f55995',
										'label' => 'Overlay Color',
										'name' => 'overlay',
										'prefix' => '',
										'type' => 'color_picker',
										'instructions' => 'Overlay color above videos and images.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'image',
												),
											),
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'video',
												),
											),
										),
										'wrapper' => array (
											'width' => 50,
											'class' => '',
											'id' => '',
										),
										'default_value' => '#000000',
									),
									array (
										'key' => 'field_549468c955996',
										'label' => 'Overlay Opacity',
										'name' => 'overlay_opacity',
										'prefix' => '',
										'type' => 'number',
										'instructions' => 'Percentage opacity for the overlay.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'image',
												),
											),
											array (
												array (
													'field' => 'field_5494684055994',
													'operator' => '==',
													'value' => 'video',
												),
											),
										),
										'wrapper' => array (
											'width' => 50,
											'class' => '',
											'id' => '',
										),
										'default_value' => 30,
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'min' => 0,
										'max' => 100,
										'step' => 5,
										'readonly' => 0,
										'disabled' => 0,
									),
									array (
										'key' => 'field_54bece444c43d',
										'label' => 'Section Caption',
										'name' => 'credits',
										'prefix' => '',
										'type' => 'textarea',
										'instructions' => 'Add a caption or credits for the section in the lower right corner.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => 'i.e. Image by John Doe',
										'maxlength' => '',
										'rows' => 2,
										'new_lines' => 'br',
										'readonly' => 0,
										'disabled' => 0,
									),
									array (
										'key' => 'field_54a464c349d2b',
										'label' => 'Extras',
										'name' => '',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
									),
									array (
										'key' => 'field_54946786c90a6',
										'label' => 'Scroll Indicator Arrow',
										'name' => 'scroll_arrow',
										'prefix' => '',
										'type' => 'true_false',
										'instructions' => 'Turn on/off the arrow indicator to scroll to next section.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
									),
									array (
										'key' => 'field_54a464dd49d2c',
										'label' => 'Animations',
										'name' => 'animations',
										'prefix' => '',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
									),
								),
							),
						),
						'min' => 1,
						'max' => '',
					),
					array (
						'key' => '54b03a96009e6',
						'name' => 'custom-section',
						'label' => 'Custom Section',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_54b03a97009eb',
								'label' => 'Content',
								'name' => '',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'left',
							),
							array (
								'key' => 'field_54be967c272b4',
								'label' => 'Vertical Alignment',
								'name' => 'vertical_alignment',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'top' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/top-align.jpg" alt="Align Top" />',
									'middle' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/middle-align.jpg"" alt="Align Middle" />',
									'bottom' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/bottom-align.jpg"" alt="Align Bottom" />',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'middle',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_54b03a97009ec',
								'label' => 'Content',
								'name' => 'content',
								'prefix' => '',
								'type' => 'wysiwyg',
								'instructions' => '(Optional) A additional text for your section. Appears below subtitle.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
							),
							array (
								'key' => 'field_54b03a97009f8',
								'label' => 'Background',
								'name' => '',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
							),
							array (
								'key' => 'field_54b03a97009f9',
								'label' => 'Text, Logo and Navigation Color',
								'name' => 'text_color',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => 'For dark backgrounds, you may want to select white.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'white' => 'White',
									'black' => 'Black',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'black',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_54b03a97009fa',
								'label' => 'Background',
								'name' => 'background',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'color' => 'Color Background',
									'image' => 'Image Background',
									'video' => 'Video Background',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'color',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_54b03a97009fd',
								'label' => 'Video Type',
								'name' => 'video_type',
								'prefix' => '',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'youtube' => 'YouTube',
									'self' => 'Self Hosted',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => '',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_54b03a97009fe',
								'label' => 'Youtube Video',
								'name' => 'youtube_video',
								'prefix' => '',
								'type' => 'url',
								'instructions' => 'Enter the Youtube Video URL.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'video',
										),
										array (
											'field' => 'field_54b03a97009fd',
											'operator' => '==',
											'value' => 'youtube',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'http://',
							),
							array (
								'key' => 'field_54b03a97009ff',
								'label' => 'Video Mp4 URL',
								'name' => 'video_mp4_url',
								'prefix' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'video',
										),
										array (
											'field' => 'field_54b03a97009fd',
											'operator' => '==',
											'value' => 'self',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
							array (
								'key' => 'field_54b03a9700a00',
								'label' => 'Video WebM URL',
								'name' => 'video_webm_url',
								'prefix' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'video',
										),
										array (
											'field' => 'field_54b03a97009fd',
											'operator' => '==',
											'value' => 'self',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
							array (
								'key' => 'field_54da2de6dea14',
								'label' => 'Video Image PlaceHolder',
								'name' => 'video_image_placeholder',
								'prefix' => '',
								'type' => 'image',
								'instructions' => 'Placeholder for images. These will display during the loading of videos and for mobile devices where video backgrounds are disabled.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_54b03a9700a01',
								'label' => 'Background Image',
								'name' => 'background_image',
								'prefix' => '',
								'type' => 'image',
								'instructions' => 'Image should be at least 1500px wide.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'image',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
							),
							array (
								'key' => 'field_54b03a9700a02',
								'label' => 'Background Color',
								'name' => 'background_color',
								'prefix' => '',
								'type' => 'color_picker',
								'instructions' => 'Solid background color for your section.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'color',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array (
								'key' => 'field_54b03a97009fb',
								'label' => 'Overlay Color',
								'name' => 'overlay',
								'prefix' => '',
								'type' => 'color_picker',
								'instructions' => 'Overlay color above videos and images.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'image',
										),
									),
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array (
									'width' => 50,
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array (
								'key' => 'field_54b03a97009fc',
								'label' => 'Overlay Opacity',
								'name' => 'overlay_opacity',
								'prefix' => '',
								'type' => 'number',
								'instructions' => 'Percentage opacity for the overlay.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'image',
										),
									),
									array (
										array (
											'field' => 'field_54b03a97009fa',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array (
									'width' => 50,
									'class' => '',
									'id' => '',
								),
								'default_value' => 30,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => 100,
								'step' => 5,
								'readonly' => 0,
								'disabled' => 0,
							),
							array (
								'key' => 'field_54b03a9700a03',
								'label' => 'Extras',
								'name' => '',
								'prefix' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
							),
							array (
								'key' => 'field_54b03a9700a04',
								'label' => 'Scroll Indicator Arrow',
								'name' => 'scroll_arrow',
								'prefix' => '',
								'type' => 'true_false',
								'instructions' => 'Turn on/off the arrow indicator to scroll to next section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 1,
							),
							array (
								'key' => 'field_54b03a9700a05',
								'label' => 'Animations',
								'name' => 'animations',
								'prefix' => '',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 1,
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '54b03dcc0b87a',
						'name' => 'custom-slides',
						'label' => 'Custom Slides',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_54b03dcc0b87b',
								'label' => 'Custom Slides',
								'name' => 'custom-slides',
								'prefix' => '',
								'type' => 'repeater',
								'instructions' => 'Click Add Slide to add a new slide to the section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'min' => '',
								'max' => '',
								'layout' => 'block',
								'button_label' => 'Add Slide',
								'sub_fields' => array (
									array (
										'key' => 'field_54b3fb0d6590e',
										'label' => 'Content',
										'name' => '',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'left',
									),
									array (
										'key' => 'field_54be96b2272b5',
										'label' => 'Vertical Alignment',
										'name' => 'vertical_alignment',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'top' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/top-align.jpg" alt="Align Top" />',
											'middle' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/middle-align.jpg"" alt="Align Middle" />',
											'bottom' => '<img src="http://themewich.com/struck/wp-content/themes/struck/images/alignment/bottom-align.jpg"" alt="Align Bottom" />',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'middle',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_54b3fb326590f',
										'label' => 'Content',
										'name' => 'content',
										'prefix' => '',
										'type' => 'wysiwyg',
										'instructions' => 'Content for your section.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
									),
									array (
										'key' => 'field_54b3fb6465910',
										'label' => 'Background',
										'name' => '',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
									),
									array (
										'key' => 'field_54b3fbd831f2b',
										'label' => 'Text, Logo and Navigation Color',
										'name' => 'text_color',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => 'For dark backgrounds, you may want to select white.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'white' => 'White',
											'black' => 'Black',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'black',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_54b3fc1931f2c',
										'label' => 'Background',
										'name' => 'background',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'color' => 'Color Background',
											'image' => 'Image Background',
											'video' => 'Video Background',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'color',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_54b3fd2456619',
										'label' => 'Video Type',
										'name' => 'video_type',
										'prefix' => '',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'video',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array (
											'youtube' => 'YouTube',
											'self' => 'Self Hosted',
										),
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
									),
									array (
										'key' => 'field_54b3fd5e5661a',
										'label' => 'Youtube Video',
										'name' => 'youtube_video',
										'prefix' => '',
										'type' => 'url',
										'instructions' => 'Enter the Youtube Video URL.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'video',
												),
												array (
													'field' => 'field_54b3fd2456619',
													'operator' => '==',
													'value' => 'youtube',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => 'http://',
									),
									array (
										'key' => 'field_54b3fdae5661c',
										'label' => 'Video Mp4 URL',
										'name' => 'video_mp4_url',
										'prefix' => '',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'video',
												),
												array (
													'field' => 'field_54b3fd2456619',
													'operator' => '==',
													'value' => 'self',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => 'http://',
									),
									array (
										'key' => 'field_54b3feca5661e',
										'label' => 'Video WebM URL',
										'name' => 'video_webm_url',
										'prefix' => '',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'video',
												),
												array (
													'field' => 'field_54b3fd2456619',
													'operator' => '==',
													'value' => 'self',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => 'http://',
									),
									array (
										'key' => 'field_54da2e55dea15',
										'label' => 'Video Image Placeholder',
										'name' => 'video_image_placeholder',
										'prefix' => '',
										'type' => 'image',
										'instructions' => 'Placeholder for images. These will display during the loading of videos and for mobile devices where video backgrounds are disabled.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'video',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_54b3ff1756620',
										'label' => 'Background Image',
										'name' => 'background_image',
										'prefix' => '',
										'type' => 'image',
										'instructions' => 'Image should be at least 1500px wide.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'image',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'medium',
										'library' => 'all',
									),
									array (
										'key' => 'field_54b3ff6056621',
										'label' => 'Background Color',
										'name' => 'background_color',
										'prefix' => '',
										'type' => 'color_picker',
										'instructions' => 'Solid background color for your section.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'color',
												),
											),
										),
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '#ffffff',
									),
									array (
										'key' => 'field_54b40f74d5d6f',
										'label' => 'Overlay Color',
										'name' => 'overlay',
										'prefix' => '',
										'type' => 'color_picker',
										'instructions' => 'Overlay color above videos and images.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'image',
												),
											),
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'video',
												),
											),
										),
										'wrapper' => array (
											'width' => 50,
											'class' => '',
											'id' => '',
										),
										'default_value' => '#000000',
									),
									array (
										'key' => 'field_54b3fca131f2f',
										'label' => 'Overlay Opacity',
										'name' => 'overlay_opacity',
										'prefix' => '',
										'type' => 'number',
										'instructions' => 'Percentage opacity for the overlay.',
										'required' => 0,
										'conditional_logic' => array (
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'image',
												),
											),
											array (
												array (
													'field' => 'field_54b3fc1931f2c',
													'operator' => '==',
													'value' => 'video',
												),
											),
										),
										'wrapper' => array (
											'width' => 50,
											'class' => '',
											'id' => '',
										),
										'default_value' => 30,
										'placeholder' => '',
										'prepend' => '',
										'append' => '%',
										'min' => 0,
										'max' => 100,
										'step' => 5,
										'readonly' => 0,
										'disabled' => 0,
									),
									array (
										'key' => 'field_54b3ffc553e50',
										'label' => 'Extras',
										'name' => '',
										'prefix' => '',
										'type' => 'tab',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'placement' => 'top',
									),
									array (
										'key' => 'field_54b3ffe053e51',
										'label' => 'Scroll Indicator Arrow',
										'name' => 'scroll_arrow',
										'prefix' => '',
										'type' => 'true_false',
										'instructions' => 'Turn on/off the arrow indicator to scroll to next section.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
									),
									array (
										'key' => 'field_54b4001553e52',
										'label' => 'Animations',
										'name' => 'animations',
										'prefix' => '',
										'type' => 'true_false',
										'instructions' => 'Turn on/off this slide\'s animations.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
			),
			array (
				'key' => 'field_5485d2a44e6ba',
				'label' => 'Section Options',
				'name' => '',
				'prefix' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
			),
			array (
				'key' => 'field_5485d4b9d8aa1',
				'label' => 'AutoScroll',
				'name' => 'scrolling_type',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => 'Turn off/on the auto scrolling feature for instead of regular scrolling for these sections.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_5485d4f6d8aa2',
				'label' => 'Section Animations',
				'name' => 'section_animations',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => 'Choose whether you want animations when the visitor enters the sections.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_54cb9d79769c2',
		'title' => 'Taxonomy Options',
		'fields' => array (
			array (
				'key' => 'field_54db8888f0ad2',
				'label' => 'Template',
				'name' => 'custom_template',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => 'Turn on to use custom template options for this taxonomy page.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'default' => 'Default (Minimal)',
					'custom' => 'Custom',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'default',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_54cb9d816a1cd',
				'label' => 'Background Image',
				'name' => 'background_image',
				'prefix' => '',
				'type' => 'image',
				'instructions' => 'Add a custom background image for this taxonomy.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54db8888f0ad2',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'fullslideshow',
				'library' => 'all',
			),
			array (
				'key' => 'field_54cba88006aae',
				'label' => 'Post Layout',
				'name' => 'post_layout',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => 'Select a custom layout for this taxonomy.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54db8888f0ad2',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'grid' => 'Grid',
					'minimal' => 'Minimal',
					'classic' => 'Classic',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 0,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_54db8b1ef0ad3',
				'label' => 'Filters',
				'name' => 'filter',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => 'Turn on/off filter links.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54db8888f0ad2',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_54db93405d9e4',
				'label' => 'Title Alignment',
				'name' => 'title_alignment',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54db8888f0ad2',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'left' => 'Left',
					'center' => 'Center',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'left',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_54db93765d9e5',
				'label' => 'Grid Crop',
				'name' => 'crop',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => 'Turn on/off cropping of grid items. Turning this off will allow the thumbnails to have their original aspect ratio.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54db8888f0ad2',
							'operator' => '==',
							'value' => 'custom',
						),
						array (
							'field' => 'field_54cba88006aae',
							'operator' => '==',
							'value' => 'grid',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_54de3af1df7d5',
				'label' => 'Grid Columns',
				'name' => 'columns',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54db8888f0ad2',
							'operator' => '==',
							'value' => 'custom',
						),
						array (
							'field' => 'field_54cba88006aae',
							'operator' => '==',
							'value' => 'grid',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					2 => 2,
					3 => 3,
					4 => 4,
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_54db94085d9e7',
				'label' => 'Alignment',
				'name' => 'alignment',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => 'Change the alignment of the filter items and posts.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54db8888f0ad2',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'left' => 'Left',
					'center' => 'Center',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'left',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'all',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_54d8f6bbb9d5b',
		'title' => 'Classic Layout Options',
		'fields' => array (
			array (
				'key' => 'field_54d8f6bb357d0',
				'label' => 'Post Alignment',
				'name' => 'alignment',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'left' => 'Left',
					'center' => 'Center',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'center',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-classic.php',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_54d8e99216fbb',
		'title' => 'Grid Options',
		'fields' => array (
			array (
				'key' => 'field_54d8e990b14a9',
				'label' => 'Crop',
				'name' => 'crop',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => 'Turn on/off cropping of grid items. Turning this off will allow the thumbnails to have their original aspect ratio.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_54de3a83f2334',
				'label' => 'Columns',
				'name' => 'columns',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => 'Number of grid columns',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					2 => 2,
					3 => 3,
					4 => 4,
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 3,
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_54d8eadcd0a36',
				'label' => 'Alignment',
				'name' => 'alignment',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => 'Change the alignment of the filter items.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'left' => 'Left',
					'center' => 'Center',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'left',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-grid.php',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_54d8f673026cd',
		'title' => 'Minimal Layout Options',
		'fields' => array (
			array (
				'key' => 'field_54d8f6723df24',
				'label' => 'Post Alignment',
				'name' => 'alignment',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => 'Select the alignment for your minimal posts.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'left' => 'Left',
					'center' => 'Center',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-minimal.php',
				),
			),
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'posts_page',
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_54d250a681a80',
		'title' => 'Post Display Options',
		'fields' => array (
			array (
				'key' => 'field_54d250a68d5ff',
				'label' => 'Posts to Display',
				'name' => 'item_type',
				'prefix' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'posts' => 'Posts',
					'portfolio' => 'Portfolio Items',
					'featured' => 'Featured Items',
					'custom' => 'Pick by Hand',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'posts',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_54d250a68d67c',
				'label' => 'Posts',
				'name' => 'items_pick',
				'prefix' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_54d250a68d5ff',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
					0 => 'post',
					1 => 'page',
					2 => 'portfolio',
				),
				'taxonomy' => '',
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
				),
				'elements' => array (
					0 => 'featured_image',
				),
				'max' => '',
				'return_format' => 'object',
			),
			array (
				'key' => 'field_54d250a68d6f2',
				'label' => 'Number of Posts Per Page',
				'name' => 'posts_number',
				'prefix' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 9,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'posts',
				'min' => 1,
				'max' => '',
				'step' => 1,
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_54d3d0496f248',
				'label' => 'Filter',
				'name' => 'filter',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => 'Allow items to be filtered with filter links?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-minimal.php',
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-grid.php',
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-classic.php',
				),
			),
		),
		'menu_order' => 3,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

endif;